app:
  datasource:
    db: ${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
  log:
    level: ${LOG_LEVEL}
  feature-flags:
    controller:
      balances: true
      transactions: true
      users: true

spring:
  application:
    name: webflux-demo-template
  liquibase:
    url: jdbc:postgresql://localhost:5432/${app.datasource.db}
    user: ${app.datasource.user}
    password: ${app.datasource.password}
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/${app.datasource.db}
    username: ${app.datasource.user}
    password: ${app.datasource.password}
  docker:
    compose:
      enabled: false
  devtools:
    add-properties: false
